version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: luwak-postgres
    restart: unless-stopped
    env_file: .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - luwak_pg_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

  postgrest:
    image: postgrest/postgrest:latest
    container_name: luwak-postgrest
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: .env.docker
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    ports:
      - "3001:3000"

  adminer:
    image: adminer
    container_name: luwak-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  luwak_pg_data:
